"""Baut data/standgericht.json (Modul 5: Das fliegende Standgericht).
Quellen: Wehrmachtberichte und eine DNB-Meldung vom 8.–18. März 1945 nach Zeitungen im Deutschen
Zeitungsportal (am Seitenbild gelesen; amtliche Bekanntmachungen, § 5 UrhG); MacDonald, The Last
Offensive (1973), S. 222 und 230; Erlass Kesselrings, BArch RH 19-IV/226, Bl. 42, am Faksimile
des Bundesarchivs gelesen (als Zitat, § 51 UrhG). Übersetzungen: eigene Arbeit (CC0).
Aufruf aus dem Wurzelverzeichnis: python tools/build-standgericht.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
D = ROOT / "data"
DZP = "https://www.deutsche-digitale-bibliothek.de/newspaper/item/"


def u(n, pg, lang, orig, tr, titel=None, titel_en=None, note=None, note_en=None):
    x = {"n": n, "pg": pg, "lang": lang}
    if titel: x["titel"], x["titel_en"] = titel, titel_en
    x["orig"] = orig
    x["en" if lang == "de" else "de"] = tr
    if note: x["note"], x["note_en"] = note, note_en
    return x


S1 = [
    u(1, "Eibenstocker Tageblatt, 8.3.1945, S. 2", "de",
      "Aus dem Führerhauptquartier, 8. März. (Funkmeldung.) Das Oberkommando der Wehrmacht gibt bekannt: […]\n\nIm Abschnitt Düsseldorf—Köln wurde unsere Front in schweren Kämpfen auf das Ostufer des Rheins zurückgedrückt. Auf dem Westufer wird noch in den Trümmern von Köln gekämpft. Gegen den Brückenkopf Bonn führt der Feind heftige Angriffe.\n\nAn der Ahr entwickelten sich lebhafte Gefechte mit feindlichen Panzerkräften, deren Spitzen bis Remagen vorstießen. Auch durch die Eifel konnten amerikanische Panzerspitzen in das Rhein—Mosel-Dreieck vordringen. Durch unsere Angriffe gegen seine tiefen Flanken erlitt der Feind schwere Verluste.",
      "From the Führer's headquarters, 8 March. (Radio report.) The High Command of the Wehrmacht announces: […]\n\nIn the Düsseldorf–Cologne sector our front was pushed back to the east bank of the Rhine in heavy fighting. On the west bank fighting continues in the ruins of Cologne. The enemy is attacking the Bonn bridgehead fiercely.\n\nOn the Ahr lively engagements developed with enemy armoured forces whose spearheads thrust as far as Remagen. American armoured spearheads were also able to push through the Eifel into the Rhine–Moselle triangle. Our attacks against his deep flanks inflicted heavy losses on the enemy.",
      "8. März: „bis Remagen“", "8 March: ‘as far as Remagen’",
      "Der Bericht vom Tag nach dem Übergang: Panzerspitzen „bis Remagen“, von einer Brücke oder einem Übergang über den Rhein kein Wort. Fraktursatz; „Rhein—Mosel-Dreieck“ so gesetzt. Zeitungsseite im Deutschen Zeitungsportal: " + DZP + "CUTSX26XYD6QN66MF2QGHT7SYY2EQPYI",
      "The report of the day after the crossing: spearheads ‘as far as Remagen’, not a word about a bridge or a crossing of the Rhine. Set in Fraktur. Newspaper page in the Deutsches Zeitungsportal: " + DZP + "CUTSX26XYD6QN66MF2QGHT7SYY2EQPYI"),
    u(2, "Donau-Bodensee-Zeitung, 10.3.1945, S. 2", "de",
      "dnb. Aus dem Führerhauptquartier, 9. März. Das Oberkommando der Wehrmacht gibt bekannt: […]\n\nIm Abschnitt Köln konnten die Amerikaner unsere Kräfte auf das Ostufer des Rheins zurückdrücken, während die Besatzung von Bonn in den Ruinen der Stadt heftigen Widerstand leistet. Im Rhein-Mosel-Dreieck gewannen die feindlichen Panzer vor allem gegen die untere Mosel hin Boden. Zwischen der Ahr und der westlichen Eifel stehen unsere Truppen in schweren Abwehrkämpfen gegen die hauptsächlich von Westen andringenden gegnerischen Verbände.",
      "dnb. From the Führer's headquarters, 9 March. The High Command of the Wehrmacht announces: […]\n\nIn the Cologne sector the Americans were able to push our forces back to the east bank of the Rhine, while the garrison of Bonn is putting up fierce resistance in the ruins of the city. In the Rhine–Moselle triangle the enemy tanks gained ground, above all towards the lower Moselle. Between the Ahr and the western Eifel our troops are engaged in heavy defensive fighting against the enemy formations pressing in mainly from the west.",
      "9. März: Remagen fehlt", "9 March: Remagen is missing",
      "Zwei Tage nach dem Übergang kommt Remagen im Bericht nicht vor. Zeitungsseite: " + DZP + "CWLB6FT3ABJWFFYNO3IMI25ITGVMUMT7. Den Bericht vom 10. März habe ich in den durchsuchten Zeitungen nicht gefunden.",
      "Two days after the crossing Remagen does not appear in the report. Newspaper page: " + DZP + "CWLB6FT3ABJWFFYNO3IMI25ITGVMUMT7. I did not find the report of 10 March in the newspapers searched."),
    u(3, "Donau-Bodensee-Zeitung, 12.3.1945, S. 1", "de",
      "Erbitterte Kämpfe an Rhein und Mosel\n\ndnb. Berlin, 11. März. […] Nach Ueberführung sämtlicher schweren Waffen und allen Gerätes wurden die Rheinbrücken bei Wesel gesprengt. Die Truppen blieben auf einer verkürzten Sehnenlinie der Rheinschleife am Feind und fingen den scharf nachdrängenden Gegner immer wieder auf. Im Schutz dichter Feuerglocken erreichten auch sie schrittweise die neuen Widerstandslinien.\n\nMit den bei Remagen über den Strom gesetzten feindlichen Kräften entwickelten sich schwere wechselvolle Kämpfe. Im Gegenangriff gewannen unsere Truppen den Nordteil von Honnef zurück und wiesen südöstlich der Stadt, bei Bruchhausen und östlich Linz feindliche Angriffe ab. Auch im Straßental nordöstlich Ohlenberg gewannen unsere Gegenstöße Boden. Der somit nach Osten abgeriegelte oder zurückgeworfene Gegner faßte eine stärkere Kampfgruppe zum Stoß nach Süden zusammen und drang auf der Rheinuferstraße bis nördlich Hönningen vor. Aber auch hier wurde er durch unsere Gegenstöße aufgefangen. Der immer noch nur aus einem schmalen Uferstreifen bestehende feindliche Brückenkopf liegt weiter unter konzentrischem Feuer unserer schweren Waffen und den fortgesetzten Angriffen unserer Flieger.",
      "Fierce fighting on the Rhine and the Moselle\n\ndnb. Berlin, 11 March. […] After all heavy weapons and all equipment had been brought across, the Rhine bridges at Wesel were blown. The troops stayed in contact with the enemy on a shortened chord line across the loop of the Rhine and caught the closely pursuing enemy again and again. Under the protection of dense curtains of fire they too reached the new lines of resistance step by step.\n\nWith the enemy forces that had crossed the river at Remagen, heavy fighting of changing fortune developed. In a counterattack our troops regained the northern part of Honnef and repulsed enemy attacks south-east of the town, at Bruchhausen and east of Linz. In the road valley north-east of Ohlenberg too our counterthrusts gained ground. The enemy, thus sealed off or thrown back to the east, assembled a stronger battle group for a thrust southward and advanced along the Rhine riverside road to north of Hönningen. But here too he was caught by our counterthrusts. The enemy bridgehead, still consisting only of a narrow strip of the bank, remains under concentric fire from our heavy weapons and continuous attacks by our airmen.",
      "11. März: „über den Strom gesetzt“", "11 March: ‘crossed the river’",
      "Kein Wehrmachtbericht, sondern eine Lagedarstellung des Deutschen Nachrichtenbüros. Bei Wesel werden die Rheinbrücken „gesprengt“, nach „Ueberführung sämtlicher schweren Waffen“; bei Remagen sind die Amerikaner „über den Strom gesetzt“. Wie, sagt der Text nicht. Fraktursatz. Zeitungsseite: " + DZP + "IRIPJYTSN57JN3245YIPDNBM6H5ZHUCE",
      "Not a Wehrmacht report but a situation summary by the German news agency (DNB). At Wesel the Rhine bridges are ‘blown’, after ‘all heavy weapons’ had been brought across; at Remagen the Americans have ‘crossed the river’. How, the text does not say. Set in Fraktur. Newspaper page: " + DZP + "IRIPJYTSN57JN3245YIPDNBM6H5ZHUCE"),
    u(4, "Donau-Bodensee-Zeitung, 12.3.1945, S. 2", "de",
      "dnb. Aus dem Führerhauptquartier, 11. März. Das Oberkommando der Wehrmacht gibt bekannt: […]\n\nNach wochenlangem heldenhaftem Widerstand vorwärts des Rheins wurden unsere Truppen befehlsgemäß aus dem Brückenkopf Wesel auf das Ostufer des Stromes zurückgenommen. […]\n\nIm Raum Remagen setzten die Amerikaner, nachdem sie aus mehreren Ortschaften am Ostufer des Rheines geworfen waren, am Nachmittag ihre Angriffe zur Gewinnung der Uferhöhen und zur Verbreiterung ihres Brückenkopfes fort. Zwischen Sinzig und Andernach werden noch mehrere Brückenköpfe auf dem Westufer des Rheines gegen heftige amerikanische Angriffe gehalten.",
      "dnb. From the Führer's headquarters, 11 March. The High Command of the Wehrmacht announces: […]\n\nAfter weeks of heroic resistance in front of the Rhine our troops were withdrawn as ordered from the Wesel bridgehead to the east bank of the river. […]\n\nIn the Remagen area the Americans, after being thrown out of several villages on the east bank of the Rhine, continued their attacks in the afternoon to gain the heights above the bank and to widen their bridgehead. Between Sinzig and Andernach several bridgeheads on the west bank of the Rhine are still being held against fierce American attacks.",
      "11. März: „ihr Brückenkopf“", "11 March: ‘their bridgehead’",
      "Der Wehrmachtbericht nennt jetzt einen amerikanischen Brückenkopf auf dem Ostufer; die Brücke, über die er entstand, nennt er nicht. So bleibt es in den Berichten bis zum 17. März, soweit sie in den durchsuchten Zeitungen vorliegen. Zeitungsseite: " + DZP + "IRIPJYTSN57JN3245YIPDNBM6H5ZHUCE",
      "The Wehrmacht report now names an American bridgehead on the east bank; the bridge by which it came into being it does not name. So it remains in the reports up to 17 March, as far as they are found in the newspapers searched. Newspaper page: " + DZP + "IRIPJYTSN57JN3245YIPDNBM6H5ZHUCE"),
]

S2 = [
    u(5, "MacDonald, S. 222", "en",
      "As for the Commander in Chief West, Field Marshal von Rundstedt, the loss of the Remagen bridge was the excuse Hitler needed to relieve the old soldier of his command. Already upset by Rundstedt's failure to hold west of the Rhine, Hitler on 8 March summoned from Italy Generalfeldmarschall Albert Kesselring, longtime Commander in Chief South (OB SUED). The next day Hitler told Kesselring to take charge in the west. In the process he emphasized that the Remagen bridgehead had to be wiped out in order to gain time for refitting and reorganizing the exhausted German units behind the moat of the Rhine. Kesselring left Berlin for his unenviable assignment the night of 9 March, the relief to be effective the next day.",
      "Für den Oberbefehlshaber West, Generalfeldmarschall von Rundstedt, war der Verlust der Brücke von Remagen der Vorwand, den Hitler brauchte, um den alten Soldaten abzulösen. Schon verärgert darüber, dass Rundstedt westlich des Rheins nicht hatte halten können, rief Hitler am 8. März Generalfeldmarschall Albert Kesselring aus Italien, den langjährigen Oberbefehlshaber Süd. Am nächsten Tag beauftragte Hitler Kesselring mit dem Befehl im Westen. Dabei betonte er, der Brückenkopf Remagen müsse beseitigt werden, um Zeit zu gewinnen, die erschöpften deutschen Verbände hinter dem Graben des Rheins aufzufrischen und neu zu gliedern. Kesselring verließ Berlin in der Nacht zum 10. März zu seiner wenig beneidenswerten Aufgabe; die Ablösung wurde am folgenden Tag wirksam.",
      "Rundstedt geht, Kesselring kommt", "Rundstedt goes, Kesselring comes",
      "„the night of 9 March“: übersetzt als Nacht zum 10. März, weil die Ablösung „the next day“ wirksam wurde. Kesselring schildert seine Zeit im Westen in seinen Erinnerungen (MacDonald, Anm. 18; nicht gemeinfrei).",
      "‘The night of 9 March’: the relief took effect ‘the next day’, i.e. 10 March. Kesselring describes his time in the west in his memoirs (MacDonald, n. 18; not in the public domain)."),
    u(6, "MacDonald, S. 230", "en",
      "Whether the reason could be ascertained or not, Hitler at the time was determined to find scapegoats to pay for the debacle. He convened a special 3-man military tribunal that acted with little regard for legal niceties. The tribunal condemned to death two majors who had commanded engineer troops in the vicinity of the bridge, Herbert Strobel and August Kraft; a lieutenant of Flakartillerie, Karl Heinz Peters; the major sent by General Hitzfeld of the LXVII Corps to assume tactical command at the bridge, Hans Scheller; and the previous tactical commander, Captain Bratge. The engineer in charge of demolitions, Captain Friesenhahn, who had been captured by the Americans, was acquitted in absentia. Because Bratge too was an American prisoner, he survived. The other four died before firing squads.",
      "Ob sich der Grund feststellen ließ oder nicht, Hitler war damals entschlossen, Sündenböcke für das Debakel büßen zu lassen. Er berief ein besonderes Militärgericht aus drei Männern, das sich um rechtliche Feinheiten wenig kümmerte. Das Gericht verurteilte zum Tode zwei Majore, die Pioniertruppen in der Nähe der Brücke befehligt hatten, Herbert Strobel und August Kraft; einen Leutnant der Flakartillerie, Karl Heinz Peters; den Major, den General Hitzfeld vom LXVII. Korps geschickt hatte, um an der Brücke den taktischen Befehl zu übernehmen, Hans Scheller; und den vorigen taktischen Kommandanten, Hauptmann Bratge. Der für die Sprengungen zuständige Pionier, Hauptmann Friesenhahn, der in amerikanische Gefangenschaft geraten war, wurde in Abwesenheit freigesprochen. Weil auch Bratge amerikanischer Gefangener war, überlebte er. Die anderen vier starben vor Erschießungskommandos.",
      "Fünf Todesurteile", "Five death sentences",
      "Opfer der NS-Justiz, nicht Schuldige: „Sündenböcke“ ist MacDonalds Wort. Das Gericht war nach dem Bundesarchiv das „Fliegende Standgericht West“ unter Generalleutnant Rudolf Hübner, das Hitler am 9. März eingesetzt hatte; die vier Offiziere wurden am 13. und 14. März bei Rimbach im Westerwald erschossen (Bundesarchiv, Online-Präsentation zum Erlass Kesselrings; neuere Darstellung). MacDonald nennt Peters „lieutenant“, der Wehrmachtbericht und Kesselrings Erlass „Oberleutnant“. Hechler erörtert das Verfahren nach MacDonalds Anm. 39 auf S. 192–212 (geschützt). Nach dem Krieg: Am 2. Februar 1967 hob das Landgericht Landshut, wo Schellers Familie lebte, im Wiederaufnahmeverfahren das Urteil gegen Major Scheller auf. Belegt ist das durch Presseberichte (NZZ, 18. September 2018; eine UPI-Meldung in der Nordwest-Zeitung vom 3. Februar 1967 war hier nicht einzusehen) und durch die Verzeichnung des Bundesarchivs: Presseausschnitte zum Wiederaufnahmeverfahren (BArch RH 24-67/20, 1966–1967) und ein Pressebericht im Nachlass Kurt Rheindorf (BArch N 1263/265). Den Urteilstext hat dieser Apparat nicht eingesehen. Versuche der Familien Scheller, Kraft und Strobel, die Urteile erneut vor Gericht zu bringen, waren in den frühen 1950er Jahren gescheitert (Kurt Kleemann, Heimatjahrbuch Kreis Ahrweiler 2010, S. 225). Unabhängig davon hebt das Gesetz zur Aufhebung nationalsozialistischer Unrechtsurteile in der Strafrechtspflege (NS-AufhG) vom 25. August 1998 Urteile auf, die aus politischen, militärischen oder weltanschaulichen Gründen unter Verstoß gegen elementare Gedanken der Gerechtigkeit ergingen (§ 1). Seit der Änderung von 2002 nennt seine Anlage (Nr. 26a) auch §§ 84 und 85 des Militärstrafgesetzbuchs, Dienstpflichtverletzung aus Furcht und Feigheit; Urteile, die darauf beruhen, sind ohne Einzelfallprüfung durch Gesetz aufgehoben (§ 2 Nr. 3; Bundestagsdrucksache 14/8276 nennt § 85 „Feigheit“ ausdrücklich). Der Wehrmachtbericht vom 18. März nennt als Gründe „Feigheit“ und „schwere Dienstpflichtverletzung im Felde“ (Einheit 7). Damit sind auch die Urteile gegen Kraft, Strobel, Peters und Bratge aufgehoben, soweit sie auf diesen Vorschriften beruhten; stützte sich ein Urteil zugleich auf andere Vorschriften, wird es nach § 3 insgesamt aufgehoben, wenn der erfasste Teil nicht nebensächlich ist. Die Urteilsgründe selbst hat dieser Apparat nicht eingesehen. Eine Bescheinigung der Staatsanwaltschaft (§ 6) stellt die Aufhebung nur fest; ob Angehörige sie beantragt haben, ist hier nicht bekannt.",
      "Victims of Nazi justice, not culprits: ‘scapegoats’ is MacDonald's word. According to the Bundesarchiv the court was the ‘Flying Court-Martial West’ under Generalleutnant Rudolf Hübner, set up by Hitler on 9 March; the four officers were shot on 13 and 14 March near Rimbach in the Westerwald (Bundesarchiv online presentation of Kesselring's decree; recent account). MacDonald calls Peters a ‘lieutenant’, the Wehrmacht report and Kesselring's decree an ‘Oberleutnant’ (first lieutenant). Hechler discusses the proceedings, according to MacDonald's n. 39, on pp. 192–212 (protected). After the war: on 2 February 1967 the Landshut regional court, where Scheller's family lived, quashed the sentence on Major Scheller in a retrial. This is documented by press reports (NZZ, 18 September 2018; a UPI report in the Nordwest-Zeitung of 3 February 1967 could not be consulted here) and by the Bundesarchiv's finding aids: press cuttings on the retrial (BArch RH 24-67/20, 1966–1967) and a press report in the papers of Kurt Rheindorf (BArch N 1263/265). This apparatus has not seen the text of the judgment. Attempts by the Scheller, Kraft and Strobel families to bring the sentences before a court again had failed in the early 1950s (Kurt Kleemann, Heimatjahrbuch Kreis Ahrweiler 2010, p. 225). Independently of this, the Act on the Annulment of Nazi Unjust Judgments in Criminal Justice (NS-AufhG) of 25 August 1998 quashes sentences passed for political, military or ideological reasons in violation of elementary principles of justice (§ 1). Since its amendment in 2002 its annex (no. 26a) also lists §§ 84 and 85 of the Military Penal Code, violation of duty out of fear and cowardice; sentences based on them are quashed by law without examination of the individual case (§ 2 no. 3; Bundestag paper 14/8276 names § 85 ‘cowardice’ expressly). The Wehrmacht report of 18 March gives ‘cowardice’ and ‘grave violation of duty in the field’ as the grounds (unit 7). The sentences on Kraft, Strobel, Peters and Bratge are therefore quashed as well, insofar as they rested on these provisions; if a sentence rested on other provisions as well, § 3 quashes it as a whole unless the part covered is of minor importance. This apparatus has not seen the grounds of the judgments. A certificate from the public prosecutor (§ 6) merely records the annulment; whether relatives applied for one is not known here."),
]

S3 = [
    u(7, "Donau-Bodensee-Zeitung, 19.3.1945, S. 1", "de",
      "dnb. Aus dem Führerhauptquartier, 18. März. Das Oberkommando der Wehrmacht gibt bekannt: […]\n\nDas Oberkommando der Wehrmacht gibt ferner bekannt:\nDurch Standgericht wurden: der Major Strobel von einem Pionierregimentsstab, der Major Scheller, Adjutant eines Armeekorps, der Major Kraft von einem Landungspionierbataillon, der Oberleutnant Peters, Führer der zum Schutz der Rheinbrücke Remagen eingesetzten Flakkräfte, und in Abwesenheit der Hauptmann Brathke, Kampfkommandant von Remagen, teils wegen Feigheit, teils wegen schwerer Dienstpflichtverletzung im Felde zum Tode verurteilt, weil sie es fahrlässig unterlassen haben, die Rheinbrücke bei Remagen rechtzeitig zu sprengen oder entschlossen zu verteidigen. Das Urteil an Strobel, Scheller, Kraft und Peters wurde sofort vollstreckt.",
      "dnb. From the Führer's headquarters, 18 March. The High Command of the Wehrmacht announces: […]\n\nThe High Command of the Wehrmacht further announces:\nBy court-martial the following were sentenced to death, partly for cowardice, partly for grave neglect of duty in the field, because they negligently failed either to blow the Rhine bridge at Remagen in time or to defend it resolutely: Major Strobel of an engineer regiment staff, Major Scheller, adjutant of an army corps, Major Kraft of a landing engineer battalion, Oberleutnant Peters, commander of the antiaircraft forces deployed to protect the Rhine bridge at Remagen, and, in absentia, Captain Brathke, combat commander of Remagen. The sentence on Strobel, Scheller, Kraft and Peters was carried out at once.",
      "18. März: die Bekanntmachung", "18 March: the announcement",
      "Erst hier, elf Tage nach dem Übergang und vier bis fünf Tage nach den Erschießungen, nennt der Wehrmachtbericht die „Rheinbrücke bei Remagen“: als Ort eines Versagens, für das Offiziere mit dem Leben bezahlt haben. Bratges Name ist entstellt, „Brathke“ in diesem Blatt, „Brakke“ oder „Belke“ in anderen (nach deren Volltext, nicht am Bild geprüft). Kraft heißt hier „von einem Landungspionierbataillon“, in anderen Zeitungen „Landespionierbataillon“. Die Meldung erschien in den Zeitungen vom 19. März; das Datum 17. März, das das Zeitungsportal für eine Ausgabe des Iserlohner Kreisanzeigers angibt, passt nicht zum Text. Zeitungsseite: " + DZP + "ZPLKES5KWSQXNJQPTVZEDQE7Q53KMTC7",
      "Only here, eleven days after the crossing and four or five days after the shootings, does the Wehrmacht report name the ‘Rhine bridge at Remagen’: as the scene of a failure for which officers have paid with their lives. Bratge's name is garbled, ‘Brathke’ in this paper, ‘Brakke’ or ‘Belke’ in others (from their full text, not checked against the image). Kraft is ‘of a landing engineer battalion’ here, ‘Landespionierbataillon’ (regional engineer battalion) in other papers. The announcement appeared in the newspapers of 19 March; the date 17 March given by the portal for one issue of the Iserlohner Kreisanzeiger does not fit the text. Newspaper page: " + DZP + "ZPLKES5KWSQXNJQPTVZEDQE7Q53KMTC7"),
]

S4 = [
    u(8, "BArch RH 19-IV/226, Bl. 42", "de",
      "Geheime Kommandosache!\nErlass des Oberbefehlshabers West.\n\nEine wichtige Rheinbrücke ist trotz sachgemässer, technischer Sprengungsvorbereitung unbeschädigt in Feindeshand gefallen, weil verantwortliche Führer infolge ihres entschlusslosen, verantwortungslosen und feigen Verhaltens den Brückenkopf aufgegeben und den Sprengungsbefehl zu spät gegeben haben.\nDie fünf schuldigen Offiziere wurden standgerichtlich zum Tode verurteilt und zwar einer von ihnen, ein Hauptmann, in Abwesenheit. Das Urteil wurde an 3 Majoren und einem Oberleutnant vollstreckt. Gegen die Sippe des nicht auffindbaren Hauptmanns ist die Sippenhaftung wirksam geworden. Vorstehendes ist sofort auf schnellstem Wege der Truppe bekanntzugeben. Es soll eine Warnung für alle sein. Wer nicht in Ehren lebt, stirbt in Schande.\n\nIch befehle hiermit erneut, dass jeder Versagensfall auf kürzestem Wege gerichtlich zu überprüfen und zu erledigen ist. Ich erwarte von den Standgerichten schärfstes Durchgreifen und grösste Härte. Der Oberbefehlshaber West gez. Kesselring, General-Feldmarschall.\n\nFür die Richtigkeit: [Unterschrift] Oberstleutnant\n[handschriftlich:] Beim Stabe bekannt gegeben [?] 21/3.45 [Unterschrift], Hptm.",
      "Top secret!\nDecree of the Commander in Chief West.\n\nAn important Rhine bridge has fallen into enemy hands undamaged despite proper technical preparation for demolition, because responsible commanders, through their irresolute, irresponsible and cowardly conduct, gave up the bridgehead and gave the order to blow too late.\nThe five guilty officers were sentenced to death by court-martial, one of them, a captain, in absentia. The sentence was carried out on 3 majors and one first lieutenant. Liability of kin has been enforced against the family of the captain, who cannot be found. The above is to be made known to the troops at once by the quickest means. Let it be a warning to all. Whoever does not live in honour dies in shame.\n\nI hereby order once again that every case of failure is to be examined and settled by court by the shortest route. I expect the courts-martial to act with the utmost severity and the greatest harshness. The Commander in Chief West, signed Kesselring, Field Marshal.\n\nCertified correct: [signature] Lieutenant Colonel\n[handwritten:] Made known to the staff [?] 21/3.45 [signature], Capt.",
      "Kesselrings Erlass", "Kesselring's decree",
      "Durchschlag einer Abschrift, „Geheime Kommandosache“, zur Weitergabe an Offiziere. Wiedergegeben als Zitat zur Dokumentation (§ 51 UrhG), am Faksimile des Bundesarchivs gelesen; das Faksimile selbst wird hier nicht gezeigt, sondern verlinkt: https://www.bundesarchiv.de/themen-entdecken/online-entdecken/dokumente-zur-zeitgeschichte/erlass-albert-kesselrings-nach-der-eroberung-der-bruecke-von-remagen/ . Das Faksimile hat „verantwortungs-losen“; die Transkription des Bundesarchivs liest „vorantwortungslosen“. Die handschriftliche Zeile ist unsicher gelesen. Der „nicht auffindbare Hauptmann“ ist Bratge, damals in amerikanischer Gefangenschaft; seine Familie traf die Sippenhaft. „Sachgemäß“ war die Sprengvorbereitung nach Kesselring; MacDonald erzählt anderes (Modul 3).",
      "Carbon copy of a transcript, ‘top secret’, for passing on to officers. Reproduced as a quotation for documentation (German copyright act § 51), read against the Bundesarchiv's facsimile; the facsimile itself is not shown here but linked: https://www.bundesarchiv.de/themen-entdecken/online-entdecken/dokumente-zur-zeitgeschichte/erlass-albert-kesselrings-nach-der-eroberung-der-bruecke-von-remagen/ . The facsimile has ‘verantwortungs-losen’; the Bundesarchiv's transcription reads ‘vorantwortungslosen’. The handwritten line is read with uncertainty. The ‘captain who cannot be found’ is Bratge, then an American prisoner; his family suffered the liability of kin. ‘Proper’ preparation is Kesselring's word; MacDonald tells it differently (module 3)."),
]

T = {
    "id": "standgericht",
    "titel": "Das fliegende Standgericht", "titel_en": "The flying court-martial",
    "autor": "Wehrmachtbericht und DNB (März 1945); MacDonald (1973); Kesselring (März 1945)",
    "autor_en": "Wehrmacht report and DNB (March 1945); MacDonald (1973); Kesselring (March 1945)",
    "jahr": "8.–21. März 1945", "jahr_en": "8–21 March 1945",
    "sprache": "de", "orig_sprache": "de", "pg_label": "", "pg_label_en": "",
    "quelle": "Wehrmachtberichte vom 8., 9., 11. und 18. März 1945 und eine Meldung des Deutschen Nachrichtenbüros vom 11. März 1945, nach dem Eibenstocker Tageblatt (8.3.) und der Donau-Bodensee-Zeitung (10., 12. und 19.3.), am Seitenbild im Deutschen Zeitungsportal gelesen; amtliche Bekanntmachungen, nach § 5 UrhG frei, die Zeitungsscans selbst nicht. Charles B. MacDonald, The Last Offensive (1973), S. 222 und 230, am Seitenbild gelesen, gemeinfrei. Erlass des Oberbefehlshabers West, Generalfeldmarschall Kesselring, März 1945, Bundesarchiv RH 19-IV/226, Bl. 42, am Faksimile gelesen und als Zitat wiedergegeben.",
    "quelle_en": "Wehrmacht reports of 8, 9, 11 and 18 March 1945 and a report of the German news agency DNB of 11 March 1945, after the Eibenstocker Tageblatt (8 March) and the Donau-Bodensee-Zeitung (10, 12 and 19 March), read against the page images in the Deutsches Zeitungsportal; official announcements, free under § 5 of the German copyright act, the newspaper scans themselves are not. Charles B. MacDonald, The Last Offensive (1973), pp. 222 and 230, read against the page images, public domain. Decree of the Commander in Chief West, Field Marshal Kesselring, March 1945, Bundesarchiv RH 19-IV/226, fol. 42, read against the facsimile and reproduced as a quotation.",
    "hinweis": "Was die Deutschen über Remagen erfuhren und was mit den Offizieren an der Brücke geschah. Der Wehrmachtbericht schweigt zuerst, spricht dann von einem Brückenkopf und nennt die Brücke erst in der Bekanntmachung der Todesurteile; Kesselrings Erlass macht die Erschießungen zur Warnung an die Truppe. Die Texte sind NS-Propaganda und Zeugnisse der NS-Justiz; sie stehen hier zur Aufklärung über die Geschichte, mit Einordnung in den Anmerkungen. Die Verurteilten waren Opfer dieser Justiz. Über das Verfahren selbst liegt keine gemeinfreie Quelle vor; was über Gericht, Ort und Datum der Erschießungen und die Sippenhaft gesagt wird, folgt der Darstellung des Bundesarchivs und ist so gekennzeichnet. Für dieses Modul gibt es keine gemeinfreien Bilder: Die Zeitungsscans und das Faksimile sind verlinkt, nicht gezeigt. Texte nach dem Druck bzw. dem Faksimile, Fraktur in Antiqua, Auslassungen […]; Übersetzungen eigene Arbeit (CC0).",
    "hinweis_en": "What the Germans learned about Remagen and what happened to the officers at the bridge. The Wehrmacht report is silent at first, then speaks of a bridgehead, and names the bridge only in the announcement of the death sentences; Kesselring's decree turns the shootings into a warning to the troops. The texts are Nazi propaganda and records of Nazi justice; they appear here for historical education, with context in the notes. Those sentenced were victims of that justice. No public-domain source exists for the proceedings themselves; what is said about the court, the place and date of the shootings and the liability of kin follows the Bundesarchiv's account and is marked as such. There are no public-domain images for this module: the newspaper scans and the facsimile are linked, not shown. Texts after the print or the facsimile, Fraktur set in roman type, omissions […]; translations my own (CC0).",
    "sections": [
        {"id": "bericht", "titel": "Was der Wehrmachtbericht sagte", "titel_en": "What the Wehrmacht report said", "zk": "Standgericht · Bericht", "zk_en": "Court-martial · Report",
         "blurb": "Am 8. März Panzerspitzen „bis Remagen“, am 9. März nichts, am 11. März ein Brückenkopf auf dem Ostufer. Bei Wesel werden die Rheinbrücken „gesprengt“; bei Remagen ist der Feind „über den Strom gesetzt“.",
         "blurb_en": "On 8 March spearheads ‘as far as Remagen’, on 9 March nothing, on 11 March a bridgehead on the east bank. At Wesel the Rhine bridges are ‘blown’; at Remagen the enemy has ‘crossed the river’.",
         "viz": "standgericht", "units": S1},
        {"id": "hitler", "titel": "Hitler sucht Schuldige", "titel_en": "Hitler looks for culprits", "zk": "Standgericht · Hitler", "zk_en": "Court-martial · Hitler",
         "blurb": "Rundstedt wird abgelöst, Kesselring soll den Brückenkopf beseitigen. Ein Dreiergericht verurteilt fünf Offiziere zum Tod; vier werden erschossen, Bratge überlebt in Gefangenschaft, Friesenhahn wird freigesprochen.",
         "blurb_en": "Rundstedt is relieved, Kesselring is to wipe out the bridgehead. A three-man tribunal sentences five officers to death; four are shot, Bratge survives as a prisoner, Friesenhahn is acquitted.",
         "units": S2},
        {"id": "okw", "titel": "Die Bekanntmachung vom 18. März", "titel_en": "The announcement of 18 March", "zk": "Standgericht · OKW", "zk_en": "Court-martial · OKW",
         "blurb": "Elf Tage nach dem Übergang nennt der Wehrmachtbericht zum ersten Mal die „Rheinbrücke bei Remagen“: in der Meldung über die Todesurteile. Bratges Name ist entstellt.",
         "blurb_en": "Eleven days after the crossing the Wehrmacht report names the ‘Rhine bridge at Remagen’ for the first time: in the announcement of the death sentences. Bratge's name is garbled.",
         "units": S3},
        {"id": "erlass", "titel": "Kesselrings Erlass", "titel_en": "Kesselring's decree", "zk": "Standgericht · Erlass", "zk_en": "Court-martial · Decree",
         "blurb": "„Es soll eine Warnung für alle sein.“ Die Erschießungen werden der Truppe bekanntgegeben, Bratges Familie in Sippenhaft genommen, jeder künftige „Versagensfall auf kürzestem Wege“ vor Gericht gestellt.",
         "blurb_en": "‘Let it be a warning to all.’ The shootings are made known to the troops, Bratge's family is subjected to liability of kin, every future ‘case of failure’ is to go to court ‘by the shortest route’.",
         "units": S4},
    ],
}
(D / "standgericht.json").write_text(json.dumps(T, ensure_ascii=False, indent=1), encoding="utf-8")

M = json.loads((D / "modules.json").read_text(encoding="utf-8"))
m = next((x for x in M["planned"] if x["id"] == "standgericht"), None) or next(x for x in M["shipped"] if x["id"] == "standgericht")
M["planned"] = [x for x in M["planned"] if x["id"] != "standgericht"]
m.update({"datei": "standgericht", "zk": "Bericht · Hitler · OKW · Erlass", "zk_en": "Report · Hitler · OKW · Decree",
          "kurz": "5 · Das fliegende Standgericht", "kurz_en": "5 · The flying court-martial",
          "warum": "Der Wehrmachtbericht schwieg über die Brücke, bis er die Todesurteile meldete. Strobel, Kraft, Scheller und Peters wurden erschossen, Bratge in Abwesenheit verurteilt, seine Familie in Sippenhaft genommen: Opfer der NS-Justiz, zur Warnung an die Truppe.",
          "warum_en": "The Wehrmacht report was silent about the bridge until it announced the death sentences. Strobel, Kraft, Scheller and Peters were shot, Bratge sentenced in absentia, his family subjected to liability of kin: victims of Nazi justice, as a warning to the troops.",
          "quelle": "Wehrmachtberichte 8.–18. März 1945 (Zeitungen im Deutschen Zeitungsportal); MacDonald (1973), S. 222, 230; Erlass Kesselrings, BArch RH 19-IV/226, Bl. 42.",
          "quelle_en": "Wehrmacht reports 8–18 March 1945 (newspapers in the Deutsches Zeitungsportal); MacDonald (1973), pp. 222, 230; Kesselring's decree, BArch RH 19-IV/226, fol. 42."})
order = ["siebter", "warum", "standgericht"]
M["shipped"] = sorted([x for x in M["shipped"] if x["id"] != "standgericht"] + [m], key=lambda x: order.index(x["id"]) if x["id"] in order else 99)
(D / "modules.json").write_text(json.dumps(M, ensure_ascii=False, indent=1), encoding="utf-8")

C = json.loads((D / "compare.json").read_text(encoding="utf-8"))
PAIRS = [
    {"id": "schuld", "titel": "Wer war schuld?", "titel_en": "Who was to blame?",
     "frage": "Wie erklären die deutschen Stellen 1945 und die US Army 1973 den Verlust der Brücke?", "frage_en": "How do the German authorities in 1945 and the US Army in 1973 explain the loss of the bridge?",
     "note": "Für den Wehrmachtbericht und Kesselring lag es an den Offizieren: „fahrlässig“, „feige“, „entschlusslos“, bei „sachgemässer“ Sprengvorbereitung. MacDonald zählt Sabotage, einen Zufallstreffer auf das Kabel und das Fehlen jeder Untersuchung auf und nennt die Verurteilten Sündenböcke.",
     "note_en": "For the Wehrmacht report and Kesselring it was the officers' fault: ‘negligent’, ‘cowardly’, ‘irresolute’, with ‘proper’ preparation for demolition. MacDonald lists sabotage, a lucky hit on the cable and the absence of any investigation, and calls those sentenced scapegoats.",
     "voices": [{"text": "standgericht", "sec": "okw", "n": [7], "wer": "Wehrmachtbericht, 18. März 1945", "wer_en": "Wehrmacht report, 18 March 1945"},
                {"text": "standgericht", "sec": "erlass", "n": [8], "wer": "Kesselring, Erlass, März 1945", "wer_en": "Kesselring, decree, March 1945"},
                {"text": "warum", "sec": "erklaerungen", "n": [22], "wer": "MacDonald 1973", "wer_en": "MacDonald 1973"}]},
    {"id": "sprengen", "titel": "Gesprengt und nicht gesprengt", "titel_en": "Blown and not blown",
     "frage": "Wie meldet man eine gesprengte und eine verlorene Brücke?", "frage_en": "How does one report a blown bridge and a lost one?",
     "note": "Am selben 11. März meldet das DNB die gesprengten Rheinbrücken bei Wesel, nach geordnetem Rückzug; die Brücke von Remagen kommt nicht vor, nur Kräfte, die „über den Strom gesetzt“ sind. Daneben MacDonald, wie die Nachricht am 7. März auf amerikanischer Seite weiterlief: binnen Stunden bis zu Eisenhower.",
     "note_en": "On the same 11 March the DNB reports the Rhine bridges at Wesel blown after an orderly withdrawal; the bridge at Remagen does not appear, only forces that have ‘crossed the river’. Beside it MacDonald on how the news travelled on the American side on 7 March: within hours up to Eisenhower.",
     "voices": [{"text": "standgericht", "sec": "bericht", "n": [3], "wer": "DNB, 11. März 1945", "wer_en": "DNB, 11 March 1945"},
                {"text": "siebter", "sec": "meldung", "n": [20], "wer": "MacDonald 1973: die Nachricht am 7. März", "wer_en": "MacDonald 1973: the news on 7 March"}]},
]
pid = {p["id"] for p in PAIRS}
C["pairs"] = [p for p in C["pairs"] if p["id"] not in pid] + PAIRS
(D / "compare.json").write_text(json.dumps(C, ensure_ascii=False, indent=1), encoding="utf-8")

TL = json.loads((D / "timeline.json").read_text(encoding="utf-8"))
st = next(s for s in TL["stations"] if s["titel"] == "Das Standgericht")
st.update({"d": "13.–18. März", "d_en": "13–18 March",
           "text": "Ein Dreiergericht verurteilt Strobel, Kraft, Scheller, Peters und in Abwesenheit Bratge zum Tod; Friesenhahn wird freigesprochen (MacDonald, S. 230). Nach dem Bundesarchiv werden die vier am 13. und 14. März bei Rimbach im Westerwald erschossen. Am 18. März meldet der Wehrmachtbericht die Urteile und nennt dabei zum ersten Mal die „Rheinbrücke bei Remagen“.",
           "text_en": "A three-man tribunal sentences Strobel, Kraft, Scheller, Peters and, in absentia, Bratge to death; Friesenhahn is acquitted (MacDonald, p. 230). According to the Bundesarchiv the four are shot on 13 and 14 March near Rimbach in the Westerwald. On 18 March the Wehrmacht report announces the sentences and, in doing so, names the ‘Rhine bridge at Remagen’ for the first time.",
           "cite": "#/text/standgericht/okw/7", "citeLabel": "Das Standgericht [7]", "citeLabel_en": "The court-martial [7]"})
ss = TL["stations"]
ss.remove(st)
ss.insert(next(i for i, s in enumerate(ss) if s["titel"] == "Der Einsturz"), st)
(D / "timeline.json").write_text(json.dumps(TL, ensure_ascii=False, indent=1), encoding="utf-8")
print("ok", sum(len(s["units"]) for s in T["sections"]), "units")
