"""Baut data/warum.json (Modul 3: Warum sie stand), trägt die Tafeln in data/plates.json und die ersten
Vergleiche in data/compare.json ein. Text: MacDonald, The Last Offensive (1973), S. 209–216 und 230,
am Seitenbild gelesen. Übersetzung ins Deutsche: eigene Arbeit (CC0).
Aufruf aus dem Wurzelverzeichnis: python tools/build-warum.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
D = ROOT / "data"


def u(n, pg, orig, de, titel=None, titel_en=None, note=None, note_en=None):
    x = {"n": n, "pg": pg}
    if titel: x["titel"], x["titel_en"] = titel, titel_en
    x["orig"], x["de"] = orig, de
    if note: x["note"], x["note_en"] = note, note_en
    return x


S1 = [
    u(1, "S. 209", "With Allied troops approaching the Rhine, the order and efficiency normally associated with things German had become submerged in a maelstrom of confused and contradictory command channels. Nowhere was this more apparent than at the railroad bridge on the southern fringe of Remagen. There a small miscellany of troops was operating under a variety of commands. An army officer, Capt. Willi Bratge, was the so-called combat commander of the entire Remagen area, ostensibly with the power of over-all command but only in event of emergency. Capt. Karl Friesenhahn, an engineer officer, was the technical or bridge commander. An antiaircraft officer, responsible to neither, commanded antiaircraft troops in the vicinity. Men of the Volkssturm were under Nazi party officials. Furthermore—though no one at Remagen yet knew it—another officer, a major, was destined soon to come to the town to supersede Bratge's command.",
      "Als die alliierten Truppen sich dem Rhein näherten, war die Ordnung und Tüchtigkeit, die man gewöhnlich mit allem Deutschen verbindet, in einem Strudel verworrener und widersprüchlicher Befehlswege untergegangen. Nirgends trat das deutlicher zutage als an der Eisenbahnbrücke am Südrand von Remagen. Dort stand ein kleines Durcheinander von Truppen unter einer Vielzahl von Kommandos. Ein Offizier des Heeres, Hauptmann Willi Bratge, war der sogenannte Kampfkommandant des ganzen Raumes Remagen, dem Anschein nach mit der Befugnis zum Gesamtbefehl, aber nur im Notfall. Hauptmann Karl Friesenhahn, ein Pionieroffizier, war der technische oder Brückenkommandant. Ein Flakoffizier, keinem von beiden verantwortlich, führte die Flaktruppen in der Umgebung. Die Männer des Volkssturms unterstanden Funktionären der NS-Partei. Außerdem sollte, was in Remagen noch niemand wusste, bald ein weiterer Offizier, ein Major, in die Stadt kommen und Bratges Befehl übernehmen.",
      "Vier Männer, vier Befehlswege", "Four men, four chains of command",
      "MacDonald erzählt die deutsche Seite nach eigener Angabe (Anm. 5) vor allem nach einer Studie Ken Hechlers für das Office of the Chief of Military History, „Seizure of the Remagen Bridge“, beruhend auf deutschen Nachkriegsmanuskripten und zeitgenössischen deutschen Akten. Die Deutschen sprechen hier also aus zweiter Hand und nach dem Krieg.",
      "MacDonald states (n. 5) that he tells the German side chiefly after a study by Ken Hechler for the Office of the Chief of Military History, ‘Seizure of the Remagen Bridge’, based on postwar German manuscripts and contemporary German records. The Germans therefore speak here at second hand and after the war."),
    u(2, "S. 209", "This confusion and contradiction was repeated at almost every level of command all along the Rhine front. Much of it was attributable to the fact that prior to March, responsibility for protecting the Rhine bridges had rested entirely with the Wehrkreise (military districts). Troops of the Wehrkreise were responsible not to any army command but to the military arm of the Nazi party, the Waffen-SS, and jealous rivalry between the two services was more the rule than the exception. As the fighting front in early March fell back from Roer to Rhine, responsibility was supposed to pass from Wehrkreis to army group and army, but in practice Wehrkreis commanders jealously held on to their command prerogatives. Furthermore, antiaircraft troops answered neither to army headquarters nor Waffen-SS but instead to the Luftwaffe; and within the Army itself the Field Army (Feldheer) vied for authority with the Replacement Army (Ersatzheer).",
      "Diese Verwirrung und dieser Widerspruch wiederholten sich auf fast jeder Befehlsebene entlang der ganzen Rheinfront. Viel davon rührte daher, dass vor dem März der Schutz der Rheinbrücken ganz bei den Wehrkreisen gelegen hatte. Die Truppen der Wehrkreise waren keinem Kommando des Heeres verantwortlich, sondern dem militärischen Arm der NS-Partei, der Waffen-SS, und eifersüchtige Rivalität zwischen beiden war eher die Regel als die Ausnahme. Als die Front Anfang März von der Rur an den Rhein zurückwich, sollte die Verantwortung vom Wehrkreis auf Heeresgruppe und Armee übergehen, aber in der Praxis hielten die Wehrkreisbefehlshaber eifersüchtig an ihren Befugnissen fest. Zudem unterstanden die Flaktruppen weder den Stäben des Heeres noch der Waffen-SS, sondern der Luftwaffe; und innerhalb des Heeres selbst stritten das Feldheer und das Ersatzheer um die Zuständigkeit.",
      None, None,
      "Die Unterstellung der Wehrkreise unter die Waffen-SS ist MacDonalds Darstellung nach Hechler; sie wird hier nicht weiter geprüft.",
      "The subordination of the Wehrkreise to the Waffen-SS is MacDonald's account after Hechler; it is not examined further here."),
    u(3, "S. 209–210", "To complicate matters further, a number of recent command changes had had an inevitable effect. On 1 February, Wehrkreis VI had relinquished authority for Remagen to Wehrkreis XII. Then, on 1 March, came the shift that took place at the height of Operation Grenade, exchange of zones between the Fifth Panzer and Fifteenth Armies. A few days later, as German troops fell back from the Roer, General Puechler's LXXIV Corps, gravitating on Bonn, might have been expected to command any bridgehead retained in the vicinity of Bonn and Remagen; but instead, Field Marshal Model at Army Group B set up a separate command, the one under General Botsch, commander of a badly depleted volks grenadier division. Botsch was to be responsible directly to Zangen's Fifteenth Army.\n\nAs General Botsch tried to appraise the situation, he ran head on into the differing views of his two superiors, Zangen and Model, as to the course the Americans presumably would follow—Model with his belief that the main thrust would be made on Bonn, Zangen with the idea that the Americans would exploit the “spout of the funnel” leading to Remagen. To be prepared for either eventuality, Botsch wanted to place his headquarters midway between the two towns, but Model insisted that he locate at or near Bonn. There Botsch ran afoul of Bonn's local defense commander, Generalmajor Richard von Bothmer, who raised questions as to just who was in command at Bonn. Trying to resolve the conflicts, Botsch spent much of the first few days of March driving back and forth between command posts of the Fifteenth Army and Army Group B and between Bonn and Remagen.",
      "Erschwerend kam hinzu, dass eine Reihe jüngster Befehlswechsel unvermeidlich nachwirkte. Am 1. Februar hatte der Wehrkreis VI die Zuständigkeit für Remagen an den Wehrkreis XII abgegeben. Dann kam am 1. März, auf dem Höhepunkt der Operation Grenade, der Tausch der Abschnitte zwischen 5. Panzerarmee und 15. Armee. Als die deutschen Truppen wenige Tage später von der Rur zurückwichen, hätte man erwarten können, dass General Püchlers LXXIV. Korps, das auf Bonn zurückging, einen etwaigen Brückenkopf bei Bonn und Remagen führen würde; stattdessen schuf Generalfeldmarschall Model bei der Heeresgruppe B ein eigenes Kommando unter General Botsch, dem Kommandeur einer stark geschwächten Volksgrenadierdivision. Botsch sollte unmittelbar Zangens 15. Armee unterstehen.\n\nAls General Botsch die Lage zu beurteilen suchte, stieß er frontal auf die unterschiedlichen Ansichten seiner beiden Vorgesetzten, Zangen und Model, über den Weg, den die Amerikaner vermutlich nehmen würden: Model glaubte, der Hauptstoß gehe auf Bonn, Zangen meinte, die Amerikaner würden den „Ausguss des Trichters“ nutzen, der nach Remagen führte. Um auf beides vorbereitet zu sein, wollte Botsch seinen Gefechtsstand zwischen beiden Städten einrichten, aber Model bestand darauf, dass er in oder bei Bonn lag. Dort geriet Botsch mit dem Bonner Kampfkommandanten, Generalmajor Richard von Bothmer, aneinander, der die Frage aufwarf, wer in Bonn eigentlich befehle. Um die Streitfragen zu klären, fuhr Botsch einen großen Teil der ersten Märztage zwischen den Gefechtsständen der 15. Armee und der Heeresgruppe B und zwischen Bonn und Remagen hin und her.",
      "Model gegen Zangen", "Model against Zangen"),
    u(4, "S. 210", "Although tiring and frustrating, these peregrinations probably established General Botsch as the one man who understood how the diverse command complex worked. Driving up the Ahr River valley toward the Fifteenth Army's headquarters early on 6 March, Botsch also got a firsthand view of pandemonium in the making as individuals and depleted units retreated pell-mell toward the Rhine. This personal knowledge of how serious matters really were well might have stood the Germans in good stead at Remagen, but General Botsch had no chance to use it.\n\nFor it was General Botsch to whom Field Marshal Model turned in the afternoon of 6 March to replace the captured General von Rothkirch in command of the LIII Corps. At 1700 Botsch left on the futile assignment of trying to resurrect the LIII Corps without even being accorded time to brief his successor, his erstwhile disputant at Bonn, General von Bothmer. Thus was lost to the Bonn-Remagen defense the one commander who, because of his knowledge of the complicated command setup and the true nature of German reverses west of the Rhine, might have forestalled what was about to happen at Remagen.",
      "So ermüdend und zermürbend diese Irrfahrten waren, machten sie General Botsch wohl zu dem einen Mann, der verstand, wie das vielgestaltige Befehlsgefüge funktionierte. Als er früh am 6. März das Ahrtal hinauf zum Gefechtsstand der 15. Armee fuhr, sah Botsch auch mit eigenen Augen das Chaos entstehen, als Einzelne und geschwächte Einheiten Hals über Kopf zum Rhein zurückwichen. Dieses eigene Wissen, wie ernst die Lage wirklich war, hätte den Deutschen in Remagen gut zustattenkommen können, aber General Botsch bekam keine Gelegenheit, es zu nutzen.\n\nDenn an General Botsch wandte sich Generalfeldmarschall Model am Nachmittag des 6. März, um den gefangenen General von Rothkirch an der Spitze des LIII. Korps zu ersetzen. Um 17 Uhr brach Botsch zu dem aussichtslosen Auftrag auf, das LIII. Korps wiederzubeleben, ohne auch nur Zeit zu bekommen, seinen Nachfolger einzuweisen, seinen früheren Widersacher in Bonn, General von Bothmer. So ging der Verteidigung von Bonn und Remagen der eine Befehlshaber verloren, der dank seiner Kenntnis des verwickelten Befehlsgefüges und des wahren Ausmaßes der deutschen Niederlagen westlich des Rheins hätte verhindern können, was in Remagen bevorstand.",
      "6. März, 17 Uhr: Botsch geht", "6 March, 1700: Botsch leaves",
      "„might have forestalled“: MacDonalds Urteil, eine Vermutung im Konjunktiv.", "‘Might have forestalled’: MacDonald's judgement, a conjecture."),
]

S2 = [
    u(5, "S. 210", "When the Fifteenth Army commander, General von Zangen, learned of Botsch's shift, he told General Hitzfeld, commander of the LXVII Corps, to send someone to Remagen to check personally on the situation there. A short while later, at 0100 on 7 March, at the same time Zangen ordered the LXVII Corps to counterattack the spout of the funnel leading to Remagen, he also told Hitzfeld the Remagen bridgehead was then the responsibility of the LXVII Corps.",
      "Als der Oberbefehlshaber der 15. Armee, General von Zangen, von Botschs Versetzung erfuhr, wies er General Hitzfeld, den Kommandierenden General des LXVII. Korps, an, jemanden nach Remagen zu schicken, der sich persönlich ein Bild von der Lage machen sollte. Kurz darauf, um 1 Uhr am 7. März, zugleich mit dem Befehl an das LXVII. Korps, gegen den Ausguss des Trichters nach Remagen zum Gegenangriff anzutreten, teilte Zangen Hitzfeld mit, der Brückenkopf Remagen liege nun in der Verantwortung des LXVII. Korps.",
      "7. März, 1 Uhr", "7 March, 0100"),
    u(6, "S. 210", "With the bulk of his troops still thirty-five miles from the Rhine, sorely beset on all sides and under orders to launch a counterattack that on the face of it was impossible, and with American troops no more than ten miles from Remagen, Hitzfeld could do little. Summoning his adjutant, Major Hans Scheller, he told him to take eight men and a radio and proceed to Remagen, there to assume command, assemble as much strength as possible, and establish a small bridgehead. He specifically warned Scheller to check immediately upon arrival as to the technical features of the Remagen railroad bridge and to make sure the bridge was prepared for demolition.",
      "Mit dem Gros seiner Truppen noch fünfunddreißig Meilen vom Rhein entfernt, von allen Seiten hart bedrängt, unter dem Befehl zu einem Gegenangriff, der offenkundig unmöglich war, und mit amerikanischen Truppen nicht mehr als zehn Meilen vor Remagen, konnte Hitzfeld wenig tun. Er rief seinen Adjutanten, Major Hans Scheller, und befahl ihm, mit acht Mann und einem Funkgerät nach Remagen zu fahren, dort den Befehl zu übernehmen, so viele Kräfte wie möglich zu sammeln und einen kleinen Brückenkopf zu bilden. Ausdrücklich schärfte er Scheller ein, sich sofort nach der Ankunft über die technischen Einzelheiten der Remagener Eisenbahnbrücke zu unterrichten und sicherzustellen, dass die Brücke zur Sprengung vorbereitet sei.",
      "Acht Mann und ein Funkgerät", "Eight men and a radio"),
    u(7, "S. 210–211", "At approximately 0200 (7 March), Major Scheller and his eight men started for Remagen in two vehicles over winding, troop-choked, blacked-out Eifel roads. In the darkness, Scheller's vehicle quickly became separated from the other, the one that carried the radio. Running low on fuel, Scheller ordered his driver to take a long detour to the south to seek out a supply installation where he might get gasoline. Shortly after 1100 on 7 March Major Scheller, still without a radio, finally reached the Remagen bridge. Sounds of battle already were discernible in the distance.",
      "Gegen 2 Uhr (7. März) brachen Major Scheller und seine acht Mann in zwei Fahrzeugen nach Remagen auf, über gewundene, von Truppen verstopfte, verdunkelte Eifelstraßen. In der Dunkelheit verlor Schellers Wagen bald das andere Fahrzeug, das mit dem Funkgerät. Weil der Treibstoff knapp wurde, ließ Scheller seinen Fahrer einen langen Umweg nach Süden nehmen, um ein Versorgungslager zu suchen, wo er Benzin bekommen konnte. Kurz nach 11 Uhr am 7. März erreichte Major Scheller, noch immer ohne Funkgerät, endlich die Brücke von Remagen. In der Ferne war schon Gefechtslärm zu hören.",
      "Ohne Funkgerät", "Without a radio",
      "Neun Stunden für eine Fahrt, die bei Tag und freier Straße kaum zwei gedauert hätte; und das Funkgerät, das Scheller später gebraucht hätte, um das Stehen der Brücke zu melden (Modul 2, Einheit 18), fuhr im anderen Wagen.",
      "Nine hours for a journey that by day on a clear road would have taken hardly two; and the radio Scheller would later have needed to report that the bridge still stood (module 2, unit 18) travelled in the other vehicle."),
]

S3 = [
    u(8, "S. 213", "Down at the bridge, confusion reigned, much as it had all morning. Since soon after daylight, frightened and disorganized groups of German troops had been fleeing across the bridge, bringing with them tales of the strength of American forces pouring down the Ahr valley. The wounded and the stragglers—tired, dispirited men with heads bowed—added stark punctuation to the accounts. Lumbering supply vehicles, horse-drawn artillery, quartermaster and other rear echelon service units created mammoth traffic jams. The jams would have been worse had not a 4-day rush job to lay planks across the railroad tracks at last been finished the night before.",
      "Unten an der Brücke herrschte Verwirrung, wie schon den ganzen Morgen. Seit kurz nach Tagesanbruch flohen verängstigte, aufgelöste Gruppen deutscher Soldaten über die Brücke und brachten Berichte über die Stärke der amerikanischen Kräfte mit, die das Ahrtal herabströmten. Die Verwundeten und die Versprengten, müde, mutlose Männer mit gesenkten Köpfen, setzten hinter diese Berichte ihre stummen Ausrufezeichen. Schwerfällige Nachschubfahrzeuge, bespannte Artillerie, Trosse und andere rückwärtige Dienste verursachten riesige Staus. Sie wären noch schlimmer gewesen, hätte man nicht am Abend zuvor eine viertägige Eilarbeit beendet, Bohlen über die Gleise zu legen.",
      "Die Brücke am Morgen", "The bridge in the morning",
      "Die Bohlen über den Gleisen machten die Eisenbahnbrücke für Fahrzeuge befahrbar: für den deutschen Rückzug, und vom Nachmittag an für den amerikanischen Vormarsch. MacDonald zählt sie später zu den Lasten, unter denen die Brücke am 17. März einstürzte (S. 230; Modul 7).",
      "The planks over the tracks made the railway bridge passable for vehicles: for the German retreat, and from the afternoon on for the American advance. MacDonald later counts them among the loads under which the bridge collapsed on 17 March (p. 230; module 7)."),
    u(9, "S. 213", "A year before the start of World War II, the Germans had devised an elaborate demolition scheme for the bridge that included installing an electric fuze connected with explosives by a cable encased in thick steel pipe. Even if the electric fuze failed to work, a primer cord might be lit by hand to set off emergency charges. Later, at the end of 1944, engineers had made plans to blow a big ditch across the Remagen end of the bridge to forestall enemy tanks until the main demolitions could be set off.",
      "Ein Jahr vor Beginn des Zweiten Weltkriegs hatten die Deutschen einen ausgeklügelten Sprengplan für die Brücke entworfen, zu dem ein elektrischer Zünder gehörte, der über ein in dickes Stahlrohr gefasstes Kabel mit den Sprengladungen verbunden war. Versagte der elektrische Zünder, konnte eine Zündschnur von Hand angezündet werden, um Notladungen auszulösen. Später, Ende 1944, hatten Pioniere geplant, am Remagener Ende der Brücke einen großen Graben zu sprengen, um feindliche Panzer aufzuhalten, bis die Hauptladungen gezündet werden konnten.",
      "Der Sprengplan von 1938", "The demolition scheme of 1938",
      "Drei Stufen: der Graben am Westende gegen Panzer, die elektrische Hauptzündung, die Zündschnur für die Notladungen. Am 7. März wurden die erste und die dritte ausgelöst; die zweite versagte (Einheiten 19–21).",
      "Three stages: the ditch at the west end against tanks, the electric main firing, the primer cord for the emergency charges. On 7 March the first and third were set off; the second failed (units 19–21)."),
    u(10, "S. 213", "Long at his post, the engineer commander at Remagen, Captain Friesenhahn, knew the demolition plan well, but only a few days before 7 March an order had arrived that complicated the task. Because a bridge at Cologne had been destroyed prematurely when an American bomb set off the explosive charges, OKW had ordered that demolitions be put in place only when the fighting front had come within eight kilometers of a bridge; and igniters were not to be attached until “demolition seems to be unavoidable.” In addition, both the order to prepare the explosives and the demolition order itself were to be issued in writing by the officer bearing tactical responsibility for the area.",
      "Der Pionierkommandant in Remagen, Hauptmann Friesenhahn, seit langem auf seinem Posten, kannte den Sprengplan gut, aber nur wenige Tage vor dem 7. März war ein Befehl eingetroffen, der die Aufgabe erschwerte. Weil in Köln eine Brücke vorzeitig zerstört worden war, als eine amerikanische Bombe die Sprengladungen auslöste, hatte das OKW befohlen, die Sprengladungen erst anzubringen, wenn die Front bis auf acht Kilometer an eine Brücke herangekommen war; und die Zünder durften erst eingesetzt werden, wenn „die Sprengung unvermeidbar erscheint“. Außerdem mussten sowohl der Befehl, die Sprengung vorzubereiten, als auch der Sprengbefehl selbst schriftlich von dem Offizier erteilt werden, der die taktische Verantwortung für den Abschnitt trug.",
      "Der Befehl des OKW", "The OKW order",
      "Nach MacDonalds Anm. 9 liegt der Befehl in amerikanischer Übersetzung als Anlage 1 zum G-2-Lagebericht der 99th Infantry Division vom 7. März 1945 vor; der deutsche Wortlaut ist hier nicht geprüft, die Anführungszeichen sind Rückübersetzung. Die Brücke in Köln: die Hohenzollernbrücke (MacDonald, Abbildung S. 190).",
      "According to MacDonald's n. 9 the order survives in American translation as Annex 1 to the 99th Infantry Division's G-2 periodic report of 7 March 1945; the German wording has not been checked here, the quotation is a translation. The bridge at Cologne: the Hohenzollern Bridge (MacDonald, illustration p. 190)."),
]

S4 = [
    u(11, "S. 213–214", "Until just before noon, 7 March, the officer bearing tactical responsibility at Remagen was Captain Bratge. In a growing lather of excitement at the hegira of German units and stragglers, Bratge early in the morning telephoned headquarters of Army Group B to ask for instructions, but he was able to get through only to a duty officer. The officer assured him that Army Group B was not particularly worried about the situation at Remagen; Bonn appeared to be the most threatened point.",
      "Bis kurz vor Mittag am 7. März war Hauptmann Bratge der Offizier, der in Remagen die taktische Verantwortung trug. In wachsender Erregung über die Flucht deutscher Einheiten und Versprengter rief Bratge früh am Morgen beim Hauptquartier der Heeresgruppe B an, um Weisungen zu erbitten, erreichte aber nur einen Offizier vom Dienst. Der versicherte ihm, die Heeresgruppe B sei über die Lage in Remagen nicht sonderlich besorgt; am meisten bedroht scheine Bonn.",
      "Bratge ruft an", "Bratge telephones"),
    u(12, "S. 214", "For actual defense of Remagen and the bridge, Captain Bratge had only thirty-six men in his own company, plus Friesenhahn's handful of engineers and a smattering of unreliable Volkssturm, the latter technically not even under Bratge's command. The antiaircraft troops that earlier had been set up on the west bank had left in midmorning, joining the retreating hordes crossing the bridge.",
      "Zur tatsächlichen Verteidigung Remagens und der Brücke hatte Hauptmann Bratge nur sechsunddreißig Mann seiner eigenen Kompanie, dazu Friesenhahns Handvoll Pioniere und ein paar unzuverlässige Volkssturmmänner, die ihm genau genommen nicht einmal unterstanden. Die Flak, die zuvor auf dem Westufer gestanden hatte, war am Vormittag abgezogen und hatte sich den zurückflutenden Massen auf der Brücke angeschlossen.",
      "Sechsunddreißig Mann", "Thirty-six men"),
    u(13, "S. 214", "General Botsch, Bratge knew, had asked Field Marshal Model at Army Group B for an entire division to defend at Bonn and a reinforced regiment at Remagen. That kind of strength, Model had replied, simply was not available. Although Model had promised some reinforcement, none had arrived. During the evening of 6 March, Bratge had tried to reach General Botsch's headquarters to ask for help, but had been unable to get through. He had no way of knowing that Botsch's headquarters had pulled out to go to Botsch's new command, the LIII Corps. An officer sent from General von Bothmer's headquarters at Bonn to give Bratge this information had wandered into American positions and been captured.",
      "General Botsch, das wusste Bratge, hatte Generalfeldmarschall Model bei der Heeresgruppe B um eine ganze Division für Bonn und ein verstärktes Regiment für Remagen gebeten. Solche Kräfte, hatte Model geantwortet, seien schlicht nicht vorhanden. Model hatte zwar etwas Verstärkung zugesagt, aber keine war gekommen. Am Abend des 6. März hatte Bratge versucht, den Gefechtsstand von General Botsch zu erreichen, um Hilfe zu erbitten, war aber nicht durchgekommen. Er konnte nicht wissen, dass Botschs Stab zu dessen neuem Kommando, dem LIII. Korps, abgezogen war. Ein Offizier, den General von Bothmers Stab in Bonn geschickt hatte, um Bratge davon zu unterrichten, war in amerikanische Stellungen geraten und gefangen genommen worden.",
      "Niemand am Telefon", "No one on the line"),
    u(14, "S. 214", "At one point Captain Bratge managed to corral the remnants of a battalion from the 3d Parachute Division and persuaded the officers to set up a defense to the southwest to block an expected American advance from the Ahr valley, but a short while later these troops melted into the fleeing columns and disappeared. When an antiaircraft unit stationed atop the Erpeler Ley withdrew, ostensibly under orders to go to Koblenz, even that strategic observation point was left unmanned.",
      "Einmal gelang es Hauptmann Bratge, die Reste eines Bataillons der 3. Fallschirmjägerdivision aufzufangen und die Offiziere zu bewegen, nach Südwesten eine Abwehr gegen einen erwarteten amerikanischen Vorstoß aus dem Ahrtal aufzubauen; doch kurz darauf lösten sich diese Truppen in den fliehenden Kolonnen auf und verschwanden. Als eine Flakeinheit auf der Erpeler Ley abzog, angeblich mit dem Befehl, nach Koblenz zu gehen, blieb selbst dieser beherrschende Beobachtungspunkt unbesetzt."),
    u(15, "S. 214", "At 1115, Bratge looked up from the unit orders he was checking at the bridge to see a red-eyed major approaching. His name, the major said, was Hans Scheller. General Hitzfeld of the LXVII Corps, he continued, had sent him to take command at Remagen.\n\nOnce Captain Bratge had assured himself that the major was, in fact, from the LXVII Corps and that his orders were legitimate, he was pleased to relinquish command. Together the two officers went to check with the engineers on progress of the demolitions. Although reports began to arrive that Americans had reached the bluffs overlooking Remagen, Scheller was reluctant to order the bridge destroyed. An artillery captain, arriving at the bridge, had insisted that his battalion and its guns were following to cross the bridge, and Major Scheller felt keenly that combat units should not be penalized by having the bridge blown in their faces, particularly when they were bringing with them precious items such as artillery pieces.",
      "Um 11.15 Uhr blickte Bratge von den Marschbefehlen auf, die er an der Brücke prüfte, und sah einen Major mit geröteten Augen herankommen. Er heiße Hans Scheller, sagte der Major. General Hitzfeld vom LXVII. Korps habe ihn geschickt, um in Remagen den Befehl zu übernehmen.\n\nNachdem Hauptmann Bratge sich vergewissert hatte, dass der Major tatsächlich vom LXVII. Korps kam und sein Befehl rechtmäßig war, gab er das Kommando gern ab. Gemeinsam gingen die beiden Offiziere zu den Pionieren, um nach dem Stand der Sprengvorbereitungen zu sehen. Obwohl Meldungen eintrafen, die Amerikaner hätten die Höhen über Remagen erreicht, zögerte Scheller, die Zerstörung der Brücke zu befehlen. Ein Artilleriehauptmann, der an die Brücke kam, hatte darauf bestanden, dass sein Bataillon mit seinen Geschützen nachkomme und übersetzen wolle, und Major Scheller war fest überzeugt, man dürfe Kampfeinheiten nicht dadurch bestrafen, dass man ihnen die Brücke vor der Nase sprengte, zumal wenn sie so kostbares Gerät wie Geschütze mitbrachten.",
      "11.15 Uhr: Scheller", "1115: Scheller",
      "Von hier an befahl nicht mehr Bratge. Das Begleitspiel nimmt diesen Wechsel auf: Bis zum Mittag hat die Rolle Befehlsgewalt, danach nur noch Einfluss.",
      "From here on Bratge no longer commanded. The companion game takes up this change: until midday the role holds command, afterwards only influence."),
]

S5 = [
    u(16, "S. 216", "Major Scheller and Captain Bratge had already crossed the bridge to the railroad tunnel. Friesenhahn hurried to join them to get the order to destroy the bridge, but concussion from a tank shell knocked him to the floor of the bridge, unconscious. Fifteen precious minutes passed before he came to his senses. Still dazed, he resumed his trek toward the tunnel.",
      "Major Scheller und Hauptmann Bratge waren schon über die Brücke zum Eisenbahntunnel gegangen. Friesenhahn eilte zu ihnen, um den Befehl zur Zerstörung der Brücke zu holen, aber die Druckwelle einer Panzergranate warf ihn bewusstlos auf die Brücke. Fünfzehn kostbare Minuten vergingen, bis er wieder zu sich kam. Noch benommen setzte er seinen Weg zum Tunnel fort.",
      "Fünfzehn Minuten", "Fifteen minutes",
      "Vorausgegangen war Friesenhahns Sprengung des Panzergrabens am Westende, „aus eigenem Entschluss“ (S. 216; Modul 2, Einheit 13).",
      "This followed Friesenhahn's blowing of the anti-tank ditch at the west end, ‘on his own initiative’ (p. 216; module 2, unit 13)."),
    u(17, "S. 216", "In the railroad tunnel, pandemonium. Terrified civilians cowering against the walls, children wailing. Reluctant Volkssturm awaiting only a chance to surrender. Clusters of apprehensive soldiers, some foreign workers, even some animals. White phosphorus shells from the American tanks across the river creating a heavy, eye-stinging smoke screen. Some soldiers caught outside the tunnel screaming as the phosphorus burned into their flesh.",
      "Im Eisenbahntunnel ein Tollhaus. Verängstigte Zivilisten an die Wände gedrückt, weinende Kinder. Widerwillige Volkssturmmänner, die nur auf die Gelegenheit warteten, sich zu ergeben. Grüppchen besorgter Soldaten, einige ausländische Arbeiter, sogar ein paar Tiere. Weiße Phosphorgranaten der amerikanischen Panzer jenseits des Flusses legten einen dichten, in den Augen brennenden Nebel. Einige Soldaten, die draußen vor dem Tunnel geblieben waren, schrien, als sich der Phosphor in ihr Fleisch brannte.",
      "Im Tunnel", "In the tunnel",
      "Die einzige Stelle bei MacDonald, an der die Menschen im Tunnel vorkommen. Wer die ausländischen Arbeiter waren, ob Zwangsarbeiter, sagt er nicht. Der Phosphor kam von amerikanischen Panzern: Gewalt beider Seiten an einem Ort.",
      "The only passage in MacDonald where the people in the tunnel appear. He does not say who the foreign workers were, or whether they were forced labourers. The phosphorus came from American tanks: violence of both sides in one place."),
    u(18, "S. 216", "As Captain Bratge rushed outside to survey the situation, he came upon Captain Friesenhahn and yelled at him to get the order from Major Scheller to blow the bridge. When Scheller gave his approval, Bratge insisted on waiting while a lieutenant wrote down the exact timing and wording of the order. Going ouside [sic] again, he shouted to Friesenhahn to blow the bridge. True to his instructions from OKW, Friesenhahn insisted at first on having the order in writing, then relented in the interest of time.",
      "Als Hauptmann Bratge hinauslief, um sich ein Bild zu machen, traf er auf Hauptmann Friesenhahn und schrie ihn an, er solle sich von Major Scheller den Befehl zur Sprengung holen. Als Scheller zustimmte, bestand Bratge darauf zu warten, bis ein Leutnant Uhrzeit und Wortlaut des Befehls genau niedergeschrieben hatte. Wieder draußen, schrie er Friesenhahn zu, die Brücke zu sprengen. Getreu seinen Anweisungen vom OKW bestand Friesenhahn zunächst darauf, den Befehl schriftlich zu haben, gab dann aber um der Zeit willen nach.",
      "Der Befehl, schriftlich", "The order, in writing",
      "Der schriftliche Befehl war Vorschrift (Einheit 10), und er war Schutz: Wer ohne ihn sprengte oder nicht sprengte, haftete mit seinem Leben. Bratge, der ihn verlangte, wurde trotzdem zum Tod verurteilt (Modul 5). „ouside“ so im Druck.",
      "The written order was required (unit 10), and it was protection: whoever blew or failed to blow without it answered with his life. Bratge, who insisted on it, was sentenced to death all the same (module 5). ‘ouside’ thus in the print."),
    u(19, "S. 216", "Warning the civilians and soldiers to take cover, Captain Friesenhahn turned the key designed to activate the electric circuit and set off the explosives. Nothing happened. He turned it again. Still nothing happened. He turned it a third time. Again, no response.",
      "Hauptmann Friesenhahn warnte die Zivilisten und Soldaten, in Deckung zu gehen, und drehte den Schlüssel, der den elektrischen Stromkreis schließen und die Ladungen zünden sollte. Nichts geschah. Er drehte ihn noch einmal. Wieder geschah nichts. Er drehte ihn ein drittes Mal. Wieder keine Antwort.",
      "Dreimal der Schlüssel", "Three turns of the key"),
    u(20, "S. 216", "Realizing that the circuit probably was broken, Friesenhahn sought a repair team to move onto the bridge; but as machine gun and tank fire riddled the ground, he saw that not enough time remained to do the job that way. He called for a volunteer to go onto the bridge and ignite the primer cord by hand. When a sergeant responded, Friesenhahn himself went with him as far as the edge of the bridge and there waited anxiously while the sergeant, crouching to avoid shells and bullets, dashed onto the bridge.",
      "Friesenhahn begriff, dass der Stromkreis wahrscheinlich unterbrochen war, und suchte einen Reparaturtrupp für die Brücke; doch als Maschinengewehr- und Panzerfeuer den Boden durchsiebte, sah er, dass dafür die Zeit nicht mehr reichte. Er rief nach einem Freiwilligen, der auf die Brücke gehen und die Zündschnur von Hand anzünden sollte. Als sich ein Feldwebel meldete, ging Friesenhahn selbst mit ihm bis an den Rand der Brücke und wartete dort angespannt, während der Feldwebel, geduckt vor Granaten und Kugeln, auf die Brücke stürzte.",
      "Ein Freiwilliger", "A volunteer",
      "Den Namen des Feldwebels nennt MacDonald nicht.", "MacDonald does not give the sergeant's name."),
    u(21, "S. 216", "After what seemed an eternity, the sergeant started back toward the east bank at a run. Seemingly endless moments passed. Had the sergeant failed? Would the primer cord ignite the charge?\n\nAt last, a sudden booming roar. Timbers flew wildly into the air. The bridge lifted as if to rise from its foundations.\n\nCowering against the explosion, Friesenhahn breathed a sigh of relief. The job was done.\n\nYet when he looked up again, the bridge was still there.",
      "Nach einer Zeit, die wie eine Ewigkeit schien, rannte der Feldwebel zum Ostufer zurück. Augenblicke vergingen, die kein Ende nehmen wollten. War der Feldwebel gescheitert? Würde die Zündschnur die Ladung zünden?\n\nEndlich ein jähes, dröhnendes Krachen. Balken flogen wild durch die Luft. Die Brücke hob sich, als wollte sie sich von ihren Fundamenten erheben.\n\nGeduckt vor der Explosion atmete Friesenhahn auf. Die Arbeit war getan.\n\nDoch als er wieder aufblickte, stand die Brücke noch da.",
      "„the bridge was still there“", "‘the bridge was still there’",
      "Dieselbe Explosion sahen die Amerikaner vom anderen Ufer (Modul 2, Einheit 14). Die Notladung genügte nicht, um die Brücke zu werfen; wie viel von ihr zündete, sagt MacDonald nicht. Die Pioniere fanden später eine nicht detonierte Ladung von etwa 500 Pfund (Modul 2, Einheit 28).",
      "The Americans saw the same explosion from the other bank (module 2, unit 14). The emergency charge was not enough to bring the bridge down; how much of it went off, MacDonald does not say. The engineers later found an undetonated charge of about 500 pounds (module 2, unit 28)."),
]

S6 = [
    u(22, "S. 230", "More speculative is the explanation of why the German demolitions failed, in the first place, to destroy the Ludendorff Bridge. Sabotage, for example, either by a German soldier or a foreign laborer, hardly could be ruled out. Since the electric circuit designed to set off the main demolitions had been tested shortly before it was to be used and was in order, something happened to the circuit shortly before Friesenhahn turned the key. Most Germans familiar with the events believed that a lucky hit from an American shell—probably fired by a tank—severed the main cable leading to the demolitions. The Americans themselves conducted no immediate postmortem, and once the bridge had fallen into the Rhine, the evidence was gone.",
      "Spekulativer ist die Erklärung, warum die deutschen Sprengungen die Ludendorff-Brücke überhaupt nicht zerstörten. Sabotage etwa, durch einen deutschen Soldaten oder einen ausländischen Arbeiter, ließ sich kaum ausschließen. Da der Stromkreis, der die Hauptsprengungen auslösen sollte, kurz vor dem Einsatz geprüft worden und in Ordnung gewesen war, muss mit ihm kurz bevor Friesenhahn den Schlüssel drehte etwas geschehen sein. Die meisten Deutschen, die die Ereignisse kannten, glaubten, ein Zufallstreffer einer amerikanischen Granate, wahrscheinlich aus einem Panzer, habe das Hauptkabel zu den Ladungen durchtrennt. Die Amerikaner selbst untersuchten die Sache nicht sofort, und als die Brücke in den Rhein gestürzt war, waren die Spuren verschwunden.",
      "Sabotage, Zufallstreffer, keine Spuren", "Sabotage, a lucky hit, no evidence",
      "Drei Möglichkeiten, keine bewiesen. Hechler hat die Vermutungen nach MacDonalds Anm. 38 ausführlich erörtert (The Bridge at Remagen, S. 212–220; geschützt, nicht abgedruckt). Die amerikanischen Pioniere schossen nach der Notsprengung Kabel durch (Modul 2, Einheiten 16, 27); das erklärt, warum danach nichts mehr zündete, nicht aber, warum der Schlüssel versagte. Zum Einsturz zehn Tage später: Modul 7.",
      "Three possibilities, none proven. According to MacDonald's n. 38 Hechler discussed the speculations at length (The Bridge at Remagen, pp. 212–220; protected, not printed). The American engineers shot through cables after the emergency demolition (module 2, units 16, 27); that explains why nothing fired afterwards, not why the key failed. On the collapse ten days later: module 7."),
]

T = {
    "id": "warum",
    "titel": "Warum sie stand", "titel_en": "Why it stood",
    "autor": "Charles B. MacDonald, The Last Offensive (1973), nach Ken Hechler", "autor_en": "Charles B. MacDonald, The Last Offensive (1973), after Ken Hechler",
    "jahr": "6.–7. März 1945", "jahr_en": "6–7 March 1945",
    "sprache": "de", "orig_sprache": "en", "pg_label": "", "pg_label_en": "",
    "quelle": "Charles B. MacDonald, The Last Offensive (United States Army in World War II. The European Theater of Operations), Washington: Office of the Chief of Military History 1973, S. 209–216 und 230, am Seitenbild des Internet Archive gelesen (CMHPub791TheLastOffensive, Public Domain Mark). Werk der US-Regierung, gemeinfrei.",
    "quelle_en": "Charles B. MacDonald, The Last Offensive (United States Army in World War II. The European Theater of Operations), Washington: Office of the Chief of Military History 1973, pp. 209–216 and 230, read against the page images of the Internet Archive (CMHPub791TheLastOffensive, Public Domain Mark). Work of the US government, in the public domain.",
    "hinweis": "Der 7. März vom Ostufer aus: Wer an der Brücke befahl, was der Sprengplan vorsah, was das OKW verlangt hatte, was im Tunnel geschah und warum die Brücke stehen blieb. Eine deutsche Quelle aus der Zeit, die gemeinfrei wäre, liegt dafür nicht vor; MacDonald erzählt die deutsche Seite nach Hechlers Studie, die auf deutschen Nachkriegsberichten beruht (Anm. 5). Die Antwort auf die Titelfrage bleibt offen, so wie bei ihm. Text nach dem Druck, Anmerkungsziffern weggelassen, Silbentrennung aufgelöst; Druckfehler mit [sic]. Übersetzung: eigene Arbeit (CC0); deutsche Dienstgrade und Truppenbezeichnungen in der Übersetzung nach dem Sprachgebrauch der Zeit.",
    "hinweis_en": "7 March from the east bank: who commanded at the bridge, what the demolition scheme provided, what OKW had required, what happened in the tunnel and why the bridge remained standing. No contemporary German source in the public domain is available for this; MacDonald tells the German side after Hechler's study, which rests on postwar German accounts (n. 5). The answer to the title's question remains open, as it does in his account. Text after the print, note numbers omitted, hyphenation resolved; misprints marked [sic]. German translation: my own (CC0); German ranks and unit names in the translation as used at the time.",
    "sections": [
        {"id": "befehle", "titel": "Viele Befehlswege", "titel_en": "Many chains of command", "zk": "Warum · Befehle", "zk_en": "Why · Commands",
         "blurb": "Ein Kampfkommandant nur für den Notfall, ein Brückenkommandant für die Technik, eine Flak, die keinem unterstand, ein Volkssturm unter der Partei; darüber zwei Vorgesetzte mit zwei Meinungen und ein General, der am Vorabend abberufen wurde.",
         "blurb_en": "A combat commander for emergencies only, a bridge commander for the technical side, antiaircraft troops answering to no one, Volkssturm under the party; above them two superiors with two opinions and a general recalled the evening before.",
         "viz": "warum", "units": S1},
        {"id": "scheller", "titel": "Scheller fährt nach Remagen", "titel_en": "Scheller drives to Remagen", "zk": "Warum · Scheller", "zk_en": "Why · Scheller",
         "blurb": "Um 1 Uhr nachts wird das LXVII. Korps zuständig. Major Scheller fährt mit acht Mann los, verliert den Wagen mit dem Funkgerät, sucht Benzin und ist kurz nach 11 Uhr an der Brücke.",
         "blurb_en": "At one in the morning the LXVII Corps becomes responsible. Major Scheller sets off with eight men, loses the vehicle with the radio, looks for petrol and reaches the bridge shortly after 1100.",
         "units": S2},
        {"id": "sprengplan", "titel": "Der Sprengplan und der Befehl des OKW", "titel_en": "The demolition scheme and the OKW order", "zk": "Warum · Sprengplan", "zk_en": "Why · Scheme",
         "blurb": "Seit 1938 ein elektrischer Zünder mit Kabel im Stahlrohr, dazu eine Zündschnur für den Notfall und ein Panzergraben am Westende. Dann der neue Befehl: Zünder erst, wenn die Sprengung unvermeidbar ist, und jeder Befehl schriftlich.",
         "blurb_en": "Since 1938 an electric fuze with a cable in steel pipe, a primer cord for emergencies and an anti-tank ditch at the west end. Then the new order: igniters only when demolition is unavoidable, and every order in writing.",
         "plates": ["mac1973_bruecke"], "units": S3},
        {"id": "bratge", "titel": "Bratge am Vormittag", "titel_en": "Bratge in the morning", "zk": "Warum · Bratge", "zk_en": "Why · Bratge",
         "blurb": "Sechsunddreißig Mann, ein Anruf, der nur einen Offizier vom Dienst erreicht, Verstärkung, die nicht kommt, Fallschirmjäger, die sich auflösen. Um 11.15 Uhr gibt Bratge den Befehl an Scheller ab, und Scheller wartet auf die Geschütze.",
         "blurb_en": "Thirty-six men, a telephone call that reaches only a duty officer, reinforcements that do not come, paratroopers who melt away. At 1115 Bratge hands command to Scheller, and Scheller waits for the guns.",
         "plates": ["adc3612c_ferne"], "units": S4},
        {"id": "tunnel", "titel": "Im Tunnel", "titel_en": "In the tunnel", "zk": "Warum · Tunnel", "zk_en": "Why · Tunnel",
         "blurb": "Zivilisten, Kinder, Volkssturm, Soldaten, ausländische Arbeiter, Phosphor vor dem Eingang. Bratge lässt den Befehl aufschreiben, Friesenhahn dreht dreimal den Schlüssel, ein Feldwebel läuft mit der Zündschnur auf die Brücke.",
         "blurb_en": "Civilians, children, Volkssturm, soldiers, foreign workers, phosphorus at the entrance. Bratge has the order written down, Friesenhahn turns the key three times, a sergeant runs onto the bridge with the primer cord.",
         "units": S5},
        {"id": "erklaerungen", "titel": "Warum?", "titel_en": "Why?", "zk": "Warum · Erklärungen", "zk_en": "Why · Explanations",
         "blurb": "Sabotage, ein Zufallstreffer auf das Kabel, keine Untersuchung: MacDonalds vorsichtige Antwort. Daneben steht, was die amerikanischen Pioniere im Film sagen.",
         "blurb_en": "Sabotage, a lucky hit on the cable, no investigation: MacDonald's cautious answer. Beside it stands what the American engineers say in the film.",
         "units": S6},
    ],
}
(D / "warum.json").write_text(json.dumps(T, ensure_ascii=False, indent=1), encoding="utf-8")

# Tafeln
P = json.loads((D / "plates.json").read_text(encoding="utf-8"))
NEW = [
    {"id": "mac1973_bruecke", "side": "bruecke", "titel": "Die Ludendorff-Brücke bei Remagen", "titel_en": "The Ludendorff Bridge at Remagen",
     "caption": "Vom Remagener Ufer aus, nach der Einnahme: die beiden Türme, zwischen ihnen die mit Bohlen belegte Fahrbahn, links Panzerfahrzeuge, rechts Trümmer. Am anderen Ende das Erpeler Ufer.",
     "caption_en": "From the Remagen bank, after the capture: the two towers, between them the planked roadway, vehicles on the left, debris on the right. At the far end the Erpel bank.",
     "source": "Photographie der US Army in MacDonald, The Last Offensive (1973), S. 224; Internet Archive CMHPub791TheLastOffensive."},
    {"id": "adc3612c_ferne", "side": "film", "titel": "Die Brücke im Dunst", "titel_en": "The bridge in the haze",
     "caption": "Die Brücke von einem Uferweg aus, im März 1945; im Vordergrund Fahrzeuge. Standbild aus der stummen Signal-Corps-Rolle.",
     "caption_en": "The bridge from a riverside road, March 1945; vehicles in the foreground. Still from the silent Signal Corps reel.",
     "source": "U.S. Army, Antiaircraft & Troops Moving Up, Remagen, Germany (National Archives, NAID 17415), 2:01; Internet Archive ADC-3612c."},
]
ids = {p["id"] for p in NEW}
P["plates"] = [p for p in P["plates"] if p["id"] not in ids] + NEW
for p in P["plates"]:
    if p["id"] == "mac1973_timmerman":
        p["caption"] = "Chef der Kompanie A, 27th Armored Infantry Battalion; nach MacDonald der erste Offizier über die Brücke. Im Text heißt er „1st Lt.“, im Abbildungsverzeichnis „2d Lt.“."
        p["caption_en"] = "Commander of Company A, 27th Armored Infantry Battalion; according to MacDonald the first officer across the bridge. The text calls him ‘1st Lt.’, the list of illustrations ‘2d Lt.’."
(D / "plates.json").write_text(json.dumps(P, ensure_ascii=False, indent=1), encoding="utf-8")

# Vergleiche
C = json.loads((D / "compare.json").read_text(encoding="utf-8"))
C["lede"] = "Stimmen nebeneinander: der Bericht der Army, die Erinnerung vor der Kamera, die deutsche Seite aus zweiter Hand. Jede Stimme verweist auf ihre Stelle im Modul."
C["lede_en"] = "Voices side by side: the Army's history, memory before the camera, the German side at second hand. Each voice points to its place in the module."
PAIRS = [
    {"id": "kabel", "titel": "Das Kabel", "titel_en": "The cable",
     "frage": "Wer durchtrennte das Kabel, und wann?", "frage_en": "Who cut the cable, and when?",
     "note": "Drei Stimmen sprechen von Kabeln, aber nicht vom selben Augenblick. Nach MacDonald versagte der deutsche Zündkreis, bevor Friesenhahn den Schlüssel drehte, also bevor Amerikaner auf der Brücke waren; die Deutschen vermuteten einen Panzertreffer. Die amerikanischen Pioniere kamen erst nach der Notsprengung und schossen Kabel durch, damit nichts mehr zündete. Dorlands Schuss erklärt das Ausbleiben weiterer Sprengungen, nicht das Versagen des Schlüssels.",
     "note_en": "Three voices speak of cables, but not of the same moment. According to MacDonald the German firing circuit failed before Friesenhahn turned the key, that is, before any American was on the bridge; the Germans suspected a hit from a tank. The American engineers came only after the emergency demolition and shot through cables so that nothing more would fire. Dorland's shot explains why no further charges went off, not why the key failed.",
     "voices": [{"text": "warum", "sec": "erklaerungen", "n": [22], "wer": "MacDonald 1973: die deutsche Sicht", "wer_en": "MacDonald 1973: the German view"}, {"text": "siebter", "sec": "uebergang", "n": [16], "wer": "MacDonald 1973: die Pioniere", "wer_en": "MacDonald 1973: the engineers"}, {"text": "siebter", "sec": "film", "n": [27], "wer": "Sergeant Dorland im Film, 1945", "wer_en": "Sergeant Dorland on film, 1945"}]},
    {"id": "vierUhr", "titel": "Um vier Uhr", "titel_en": "At four o'clock",
     "frage": "Wann sollte die Brücke gesprengt werden?", "frage_en": "When was the bridge to be blown?",
     "note": "Ein Zivilist in Sinzig nannte 16 Uhr, Engeman erinnerte sich an dieselbe Meldung. MacDonald stellt fest, die Deutschen hätten keinen festen Zeitplan gehabt: Ihr Sprengbefehl hing an einem schriftlichen Befehl und an Geschützen, die noch über den Fluss sollten.",
     "note_en": "A civilian at Sinzig named 1600, and Engeman remembered the same message. MacDonald states that the Germans had no fixed schedule: their demolition depended on a written order and on guns still meant to cross the river.",
     "voices": [{"text": "siebter", "sec": "hoehe", "n": [12], "wer": "MacDonald 1973: die Meldung aus Sinzig", "wer_en": "MacDonald 1973: the message from Sinzig"}, {"text": "siebter", "sec": "film", "n": [23], "wer": "Oberstleutnant Engeman im Film, 1945", "wer_en": "Lieutenant Colonel Engeman on film, 1945"}, {"text": "warum", "sec": "bratge", "n": [15], "wer": "MacDonald 1973: Scheller zögert", "wer_en": "MacDonald 1973: Scheller hesitates"}]},
    {"id": "schriftlich", "titel": "Der Befehl, schriftlich", "titel_en": "The order, in writing",
     "frage": "Warum dauerte der Sprengbefehl?", "frage_en": "Why did the order to blow take so long?",
     "note": "Der Befehl des OKW verlangte Schriftform; Bratge ließ den Befehl niederschreiben, Friesenhahn wollte ihn erst schriftlich und gab dann nach. Die Vorschrift sollte vorzeitige Sprengungen verhindern; am 7. März kostete sie Minuten.",
     "note_en": "The OKW order required the written form; Bratge had the order written down, Friesenhahn wanted it in writing at first and then gave way. The rule was meant to prevent premature demolitions; on 7 March it cost minutes.",
     "voices": [{"text": "warum", "sec": "sprengplan", "n": [10], "wer": "MacDonald 1973: der Befehl des OKW", "wer_en": "MacDonald 1973: the OKW order"}, {"text": "warum", "sec": "tunnel", "n": [18], "wer": "MacDonald 1973: im Tunnel", "wer_en": "MacDonald 1973: in the tunnel"}]},
    {"id": "blick", "titel": "Die Brücke steht noch", "titel_en": "The bridge still stands",
     "frage": "Wer sah die Brücke stehen?", "frage_en": "Who saw the bridge standing?",
     "note": "Dreimal derselbe Satz an diesem Tag: Burrows auf der Höhe, Friesenhahn nach der Sprengung am Ostufer, Timmermans Männer am Westufer. MacDonald erzählt beide Ufer mit demselben Bild.",
     "note_en": "Three times the same sentence on that day: Burrows on the heights, Friesenhahn on the east bank after the demolition, Timmerman's men on the west bank. MacDonald tells both banks with the same image.",
     "voices": [{"text": "siebter", "sec": "vormarsch", "n": [8], "wer": "MacDonald 1973: Burrows auf der Höhe", "wer_en": "MacDonald 1973: Burrows on the heights"}, {"text": "warum", "sec": "tunnel", "n": [21], "wer": "MacDonald 1973: Friesenhahn am Ostufer", "wer_en": "MacDonald 1973: Friesenhahn on the east bank"}, {"text": "siebter", "sec": "uebergang", "n": [14], "wer": "MacDonald 1973: Timmermans Männer", "wer_en": "MacDonald 1973: Timmerman's men"}]},
]
pid = {p["id"] for p in PAIRS}
C["pairs"] = [p for p in C.get("pairs", []) if p["id"] not in pid] + PAIRS
(D / "compare.json").write_text(json.dumps(C, ensure_ascii=False, indent=1), encoding="utf-8")

# Modulliste
M = json.loads((D / "modules.json").read_text(encoding="utf-8"))
m = next((x for x in M["planned"] if x["id"] == "warum"), None) or next(x for x in M["shipped"] if x["id"] == "warum")
M["planned"] = [x for x in M["planned"] if x["id"] != "warum"]
m.update({"datei": "warum", "zk": "Befehle · Scheller · Sprengplan · Bratge · Tunnel · Erklärungen", "zk_en": "Commands · Scheller · Scheme · Bratge · Tunnel · Explanations",
          "kurz": "3 · Warum sie stand", "kurz_en": "3 · Why it stood",
          "warum": "Vier Männer mit vier Befehlswegen, ein Major ohne Funkgerät, ein Befehl, der schriftlich sein musste, Menschen im Tunnel, dreimal ein Schlüssel ohne Wirkung, eine Notladung, die die Brücke nur hob. Warum der Zündkreis versagte, bleibt offen.",
          "warum_en": "Four men with four chains of command, a major without a radio, an order that had to be in writing, people in the tunnel, three turns of a key to no effect, an emergency charge that only lifted the bridge. Why the firing circuit failed remains open.",
          "quelle": "MacDonald, The Last Offensive (1973), S. 209–216 und 230 (nach Hechlers Studie zur deutschen Seite).",
          "quelle_en": "MacDonald, The Last Offensive (1973), pp. 209–216 and 230 (after Hechler's study of the German side)."})
order = ["siebter", "warum"]
M["shipped"] = sorted([x for x in M["shipped"] if x["id"] != "warum"] + [m], key=lambda x: order.index(x["id"]) if x["id"] in order else 99)
(D / "modules.json").write_text(json.dumps(M, ensure_ascii=False, indent=1), encoding="utf-8")
print("ok", sum(len(s["units"]) for s in T["sections"]), "units,", len(C["pairs"]), "pairs")
